<?php
/**
 * A fresh exam to check the student exam page by hand. DEV ONLY.
 *
 *   php database/dev/handcheck_exam.php
 *
 * Writes to the database named in config/config.php - your working local
 * database, not the test database the suites wipe. Run it again whenever you
 * want a clean paper: every run throws away the previous hand-check exam, its
 * attempts and its questions, and builds new ones. The Teacher, Student and
 * Subject are reused, and both passwords are reset so they can be printed.
 *
 * What it touches, and nothing else:
 *   - the Teacher whose email is handcheck.teacher@exam.local
 *   - the Student whose full name is exactly "HANDCHECK Student"
 *   - the Subject whose code is HANDCHECK, and only if that Teacher owns it
 *   - exams, attempts and questions inside that Subject
 * Every one of those is created here with the HANDCHECK name. If a row with
 * one of those identifiers exists but was not made by this script, it stops
 * rather than adopting someone else's data.
 *
 * Students are made the way the app makes them: a real class (never the
 * UNASSIGNED placeholder), an admission number generated by the import's own
 * ADM/<year>/NNNN sequence, and User::create, so the users table's CHECK
 * constraint is met by the same path the admin screen uses.
 *
 * It refuses to run unless the database host is this machine. That is not
 * proof of a dev machine: a school server running XAMPP also talks to MySQL on
 * localhost. Do not copy database/dev/ onto a school server.
 */

declare(strict_types=1);

if (PHP_SAPI !== 'cli') {
    http_response_code(404);
    exit;
}

define('APP_ROOT', dirname(__DIR__, 2));

function fail(string $message): void
{
    fwrite(STDERR, "REFUSING TO RUN: $message\n");
    exit(1);
}

$configFile = APP_ROOT . '/config/config.php';
if (!is_file($configFile)) {
    fail('no config/config.php.');
}
require $configFile;

// ---- Guards ----------------------------------------------------------------

if (!in_array(strtolower(DB_HOST), ['localhost', '127.0.0.1', '::1'], true)) {
    fail("DB_HOST is '" . DB_HOST . "'. This script only writes to a database on this machine.");
}

// The suites drop and rebuild the test database, so a hand-check exam there
// would vanish on the next run. And config.php must never name it anyway.
if (strpos(DB_NAME, 'test') !== false || strpos(DB_NAME, 'dryrun') !== false) {
    fail("DB_NAME '" . DB_NAME . "' is a test database. Point config/config.php at your working local database.");
}

require_once APP_ROOT . '/app/core/helpers.php';

spl_autoload_register(static function (string $class): void {
    foreach (['core', 'models'] as $dir) {
        $file = APP_ROOT . '/app/' . $dir . '/' . $class . '.php';
        if (is_file($file)) {
            require_once $file;
            return;
        }
    }
});

// ---- Names -----------------------------------------------------------------

const PREFIX        = 'HANDCHECK';
const TEACHER_EMAIL = 'handcheck.teacher@exam.local';
const TEACHER_NAME  = PREFIX . ' Teacher';
const STUDENT_NAME  = PREFIX . ' Student';
const SUBJECT_CODE  = PREFIX;
const SUBJECT_TITLE = PREFIX . ' Subject';
const EXAM_TITLE    = PREFIX . ' Exam';

$db = Database::getInstance();

function one(string $sql, array $params = []): ?array
{
    $stmt = Database::getInstance()->prepare($sql);
    $stmt->execute($params);
    $row = $stmt->fetch();
    return $row === false ? null : $row;
}

// ---- Teacher ---------------------------------------------------------------

$users = new User();

$teacherPassword = Password::generate();
$teacher = $users->findByEmail(TEACHER_EMAIL);

if ($teacher === null) {
    $teacherId = $users->create(TEACHER_NAME, TEACHER_EMAIL, $teacherPassword, 'lecturer');
    $teacherState = 'created';
} else {
    if ($teacher['full_name'] !== TEACHER_NAME || $teacher['role'] !== 'lecturer') {
        fail(TEACHER_EMAIL . ' belongs to "' . $teacher['full_name'] . '", not the hand-check Teacher.');
    }
    $teacherId = (int) $teacher['id'];
    $users->setPasswordHash($teacherId, Password::hash($teacherPassword));
    $teacherState = 'reused, password reset';
}

// ---- Student ---------------------------------------------------------------

$studentPassword = Password::generate();

$stmt = $db->prepare("SELECT * FROM users WHERE full_name = ?");
$stmt->execute([STUDENT_NAME]);
$matches = $stmt->fetchAll();

if (count($matches) > 1) {
    fail('more than one user is named "' . STUDENT_NAME . '". Remove the extra one by hand.');
}

if ($matches === []) {
    // A real class, as the admin form insists: never the placeholder.
    $classes = (new SchoolClass())->selectable();
    if ($classes === []) {
        fail('the classes table has no real class to put the Student in.');
    }
    $class = $classes[0];

    // The import's own generator, continuing the ADM/<year>/NNNN sequence.
    [$row] = (new StudentImport())->assignAdmissionNumbers([
        ['full_name' => STUDENT_NAME, 'admission_no' => '', 'class_id' => (int) $class['id']],
    ]);
    $admissionNo = $row['admission_no'];

    // The same format and uniqueness rules AdminController::storeUser applies.
    if (!preg_match('/^[A-Z0-9][A-Z0-9\/\-]{2,29}$/', $admissionNo)) {
        fail("generated admission number '$admissionNo' is not a valid format.");
    }
    if ($users->findByAdmissionNo($admissionNo) !== null) {
        fail("generated admission number '$admissionNo' is already in use.");
    }

    $studentId = $users->create(STUDENT_NAME, null, $studentPassword, 'student', $admissionNo, (int) $class['id']);
    $studentState = 'created';
} else {
    $student = $matches[0];
    if ($student['role'] !== 'student' || $student['admission_no'] === null) {
        fail('"' . STUDENT_NAME . '" exists but is not a student with an admission number.');
    }
    $studentId = (int) $student['id'];
    $users->setPasswordHash($studentId, Password::hash($studentPassword));
    if ($student['status'] !== 'active') {
        $users->setStatus($studentId, 'active');
    }
    $studentState = 'reused, password reset';
}

$student = $users->findWithClass($studentId);

// ---- Subject and enrolment -------------------------------------------------

$courses = new Course();
$subject = $courses->findByCode(SUBJECT_CODE);

if ($subject === null) {
    $subjectId = $courses->create(SUBJECT_CODE, SUBJECT_TITLE, $teacherId);
    $subjectState = 'created';
} else {
    if ((int) $subject['lecturer_id'] !== $teacherId || $subject['title'] !== SUBJECT_TITLE) {
        fail('a Subject with code ' . SUBJECT_CODE . ' exists but was not made by this script.');
    }
    $subjectId = (int) $subject['id'];
    $subjectState = 'reused';
}

$enrolments = new Enrollment();
if (!$enrolments->isEnrolled($studentId, $subjectId)) {
    $enrolments->enroll($studentId, $subjectId);
}

// ---- Throw away the previous hand-check exam -------------------------------
//
// Everything below is scoped to the HANDCHECK Subject. Attempts go first: they
// reference the exam and the questions without cascading. Deleting an attempt
// cascades to its frozen paper, its answers, its activity log, and its pauses,
// events and blocked-action counts; deleting an exam cascades to its pool;
// deleting a question cascades to its options.

$db->beginTransaction();
try {
    $examIds = $db->prepare("SELECT id FROM exams WHERE course_id = ?");
    $examIds->execute([$subjectId]);
    $examIds = $examIds->fetchAll(PDO::FETCH_COLUMN);

    $removedAttempts = 0;
    $removedExams    = 0;
    $removedChildren = ['attempt_locks' => 0, 'attempt_events' => 0, 'attempt_blocked_actions' => 0];
    if ($examIds !== []) {
        $in = implode(',', array_fill(0, count($examIds), '?'));

        // Counted before and checked after, so a cascade that stopped working
        // shows up here rather than as rows quietly left behind.
        $childCount = static function (string $table) use ($db, $in, $examIds): int {
            $stmt = $db->prepare("SELECT COUNT(*) FROM $table
                                   WHERE attempt_id IN (SELECT id FROM exam_attempts WHERE exam_id IN ($in))");
            $stmt->execute($examIds);
            return (int) $stmt->fetchColumn();
        };
        foreach (array_keys($removedChildren) as $table) {
            $removedChildren[$table] = $childCount($table);
        }
        $attemptIds = $db->prepare("SELECT id FROM exam_attempts WHERE exam_id IN ($in)");
        $attemptIds->execute($examIds);
        $attemptIds = $attemptIds->fetchAll(PDO::FETCH_COLUMN);

        $del = $db->prepare("DELETE FROM exam_attempts WHERE exam_id IN ($in)");
        $del->execute($examIds);
        $removedAttempts = $del->rowCount();

        if ($attemptIds !== []) {
            $ids = implode(',', array_fill(0, count($attemptIds), '?'));
            foreach (array_keys($removedChildren) as $table) {
                $left = $db->prepare("SELECT COUNT(*) FROM $table WHERE attempt_id IN ($ids)");
                $left->execute($attemptIds);
                if ((int) $left->fetchColumn() !== 0) {
                    throw new RuntimeException("$table rows survived deleting their attempts.");
                }
            }
        }

        $del = $db->prepare("DELETE FROM exams WHERE id IN ($in) AND course_id = ?");
        $del->execute(array_merge($examIds, [$subjectId]));
        $removedExams = $del->rowCount();
    }

    $del = $db->prepare("DELETE FROM questions WHERE course_id = ? AND created_by = ?");
    $del->execute([$subjectId, $teacherId]);
    $removedQuestions = $del->rowCount();

    $db->commit();
} catch (Throwable $e) {
    $db->rollBack();
    throw $e;
}

// ---- A fresh paper ---------------------------------------------------------

$questions = new Question();

// Two lines, markup characters, quotes and Yoruba diacritics: every one must
// show on screen exactly as typed, and none may be read as HTML.
$q1 = $questions->createMcq(
    $subjectId,
    "Tom & Jerry <b>not bold</b> \"quoted\" ẹ ọ ṣ ń\nWhich of these is true when x = 3 and a and b are both true?",
    2,
    $teacherId,
    ['x < 5', 'a & b is false', 'x > 5', '<i>none</i> of these'],
    0
);

$q2 = $questions->createMcq(
    $subjectId,
    'What is the capital of Nigeria?',
    1,
    $teacherId,
    ['Lagos', 'Abuja', 'Kano', 'Ibadan'],
    1
);

$q3 = $questions->createEssay(
    $subjectId,
    'Describe the water cycle in your own words.',
    10,
    $teacherId
);

$q4 = $questions->createEssay(
    $subjectId,
    'Explain one cause of inflation and one way a government can respond to it.',
    10,
    $teacherId
);

$now   = time();
$exams = new Exam();

$examId = $exams->create(
    $subjectId,
    EXAM_TITLE,
    "Hand-check paper. Answer all four questions.\nYour answers are saved as you go.",
    30,
    date('Y-m-d H:i:s', $now),
    date('Y-m-d H:i:s', $now + 3 * 3600),
    4,
    50
);

(new ExamPool())->replace($examId, [$q1, $q2, $q3, $q4]);

// The checks publishExam() makes, so this cannot publish a paper the Teacher's
// own screen would refuse.
$exam = $exams->find($examId);
if ((new ExamPool())->countForExam($examId) < (int) $exam['questions_per_attempt']) {
    fail('the pool is smaller than the draw. Nothing was published.');
}
$exams->setStatus($examId, 'published');
$exam = $exams->find($examId);

// ---- Report ----------------------------------------------------------------

$base = 'http://localhost' . BASE_URL;

echo "\n";
echo "Hand-check exam ready in database '" . DB_NAME . "' on " . DB_HOST . "\n";
echo "\n";
printf("Removed from the last run: %d exam(s), %d attempt(s), %d question(s)\n",
    $removedExams, $removedAttempts, $removedQuestions);
printf("          with the attempts: %d lock(s), %d event(s), %d blocked-action row(s)\n",
    $removedChildren['attempt_locks'], $removedChildren['attempt_events'], $removedChildren['attempt_blocked_actions']);
echo "\n";
printf("Teacher   %s (%s)\n", TEACHER_NAME, $teacherState);
printf("          Email      %s\n", TEACHER_EMAIL);
printf("          Password   %s\n", $teacherPassword);
echo "\n";
printf("Student   %s (%s)\n", $student['full_name'], $studentState);
printf("          Class      %s\n", SchoolClass::labelFor($student));
printf("          Admission  %s\n", $student['admission_no']);
printf("          Password   %s\n", $studentPassword);
echo "\n";
printf("Subject   %s, %s (%s), Student enrolled\n", SUBJECT_CODE, SUBJECT_TITLE, $subjectState);
echo "\n";
printf("Exam      %s, published\n", $exam['title']);
printf("          Window opens   %s\n", $exam['window_start']);
printf("          Window closes  %s\n", $exam['window_end']);
printf("          Duration       %d minutes, %d questions (2 MCQ, 2 essay)\n",
    (int) $exam['duration_minutes'], (int) $exam['questions_per_attempt']);
echo "\n";
printf("Sign in   %sauth/login\n", $base);
printf("Exam      %sstudent/attempt/%d\n", $base, $examId);
echo "\n";
